### ISSUE TITLE
Force closing when trying to implement BetterASyncTask

### ISSUE THREAD

**Issue by adjdred** [mttkay/droid-fu#10]
Hi

Hoping someone can point me in the right direction as to how to implement the betterasynctask.

I have been trying to make an example project to test out the library but when ever i go to run the app it keeps force closing. Could you provide an example project or files which demonstrates how to use it.

Thanks
Adam

**Comment by hwrdprkns** [comment]
Use it like you normally would -- except put the stuff that was in doInBackground to doCheckedInBackground.

Its a pretty simple thing to implement. Also make sure your application extends the com.github.droidfu application or the task won't be able to create itself.

Also, this is not an issue with his code -- consider posting on a help website like stackoverflow.com so others can see your questions as well.

**Comment by adjdred** [comment]
hi hwrdprkns

I have submitted a question to stackoverflow with an example app.

http://stackoverflow.com/questions/3670641/force-close-when-tying-to-use-betterasynctask-in-droid-fu-android

Thanks
Adam

**Comment by hwrdprkns** [comment]
This should be closed -- it was solved.

**Comment by adjdred** [comment]
this isnt an issue and just a learning curve. was added to stackoverflow.

more docs needed for the library
