### ISSUE TITLE
Maveb POM Build - Latest Version does not build

### ISSUE THREAD

**Issue by mimminito** [mttkay/droid-fu#18]
Hey,

Since you have updated the POM file to Android 2.3, I am unable to build Droid-Fu.

I keep getting Build Failures regarding the android maps jar, and how its unable to find them on the repo? Im very new to Maven, so its a little tricky for me to solve this.

Any help would be appreciated.

**Comment by futtetennista** [comment]
Try this tool: https://github.com/mosabua/maven-android-sdk-deployer. It should install the android.jar and maps.jar in your local repository.
