### ISSUE TITLE
OAuthConsumer

### ISSUE THREAD

**Issue by Antek** [mttkay/droid-fu#2]
Hi there. I have difficulties building this jar file.
When loading your project in eclipse, this project has several errors. I had to delete the test files from the build path, after that i had an error OAuthConsumer couldn't be found.

I tried building the Jar file a different way, with mvn, there I got an error android:android:jar:1.5_r2 is missing. Too be honest I don't know how to link it. If you could give me a hint there.. 

Thanks in advance,
Antek

**Comment by Antek** [comment]
Too complete this issue. I've excluded the main/test/main.java from my build path, because it was missing, then I got a new error in BetterHttpRequest that OAthConsumer object is missing.

**Comment by mttkay** [comment]
Hi,

you need the Android JAR as an artifact in your local Maven repository. Unfortunately, Google does not seem to be willing to add the Android JARs to Maven Central, so you have to install it manually (that's pretty easy though).

Instructions here:
http://code.google.com/p/maven-android-plugin/wiki/GettingStarted

PS: everything should be fine after doing that. don't do stuff like deleting tests... that will most certainly break the build.

**Comment by mttkay** [comment]
Did you manage to get it working? Here's the step-by-step instructions (the maven-android-sdk-deployer is brand new, hadn't worked with it before myself):
1. Update Droid-Fu to the latest version (I just committed a change which affects the build process)
2. download the maven-android SDK deployer from http://github.com/mosabua/maven-android-sdk-deployer/archives/master
3. OR -
   git clone git://github.com/mosabua/maven-android-sdk-deployer.git
4. go to the folder where you cloned/unzipped the archive
5. go to platforms/android-1.5 directory
6. do $mvn install -Dandroid.sdk.path=/path/to/your/android/sdk
7. go to the folder where you cloned/unzipped droid-fu
8. do $mvn install -DcopyTo=/path/to/your/apps/lib/folder

that should do the job.

**Comment by mttkay** [comment]
if you still have problems... I just uploaded a recent build to the downloads section --> http://github.com/kaeppler/droid-fu/downloads

but keep in mind that I will only occasionally update that file. syncing with master is your best bet ATM, since this library is still in early development.

**Comment by matt-lethargic** [comment]
Hi is this project dead now? I'd like to be able to keep transparent file transparent. If this isn't going to happen or if this project is dead I'd like to know now so I can find a different solution. Thanks 
Matt

**Comment by mttkay** [comment]
it's not dead, just on hold. I have been busy with other projects lately, but I'll get back to it as part of Qype's next iteration on Qype for Android.

**Comment by matt-lethargic** [comment]
Oh cool. Right I have an on thread question. I've followed the process above and created the file droid-fu-1.0-SNAPSHOT.jar in my lib folder. Since that I've changed the code slightly in an attempt to be able to set the scaleType of the image. I've create a public method call setScaleType and run the above command (8) again. In Eclipse I've tried using that method in my code but it doesn't appear in the autocomplete and won't compile.

I also expanded the "Referenced Libraries" folder in the package explorer and expanded down to the WebImageView.class and the method is listed there.

Any ideas what I'm doing wrong or steps i've missed out?!

Thanks
Matt

**Comment by matt-lethargic** [comment]
ignore me.... it worked :/

**Comment by mttkay** [comment]
FYI: droid-fu is now completely decoupled from signpost. The signed() method has been removed. Please use an HttpClient RequestInterceptor to sign requests from now on, e.g.:

public class OAuthRequestInterceptor implements HttpRequestInterceptor {

```
public void process(HttpRequest request, HttpContext context) throws HttpException, IOException {
    try {
        if (request instanceof RequestWrapper) {
            RequestWrapper wrapper = (RequestWrapper) request;
            HttpUriRequest uriRequest = (HttpUriRequest) wrapper.getOriginal();

            // remove any existing Auth header, since this may be invoked as part of a
            // request-retry cycle
            uriRequest.removeHeaders(OAuth.HTTP_AUTHORIZATION_HEADER);

            // sign the original request (Signpost needs the URL, so the wrapper is not enough)
            OAuthSystem.getConsumer().sign(uriRequest);

            // copy the header over to the wrapper
            Header authHeader = uriRequest.getHeaders(OAuth.HTTP_AUTHORIZATION_HEADER)[0];
            request.setHeader(authHeader);

            // Log.d("BetterHttp/OAuth " + System.currentTimeMillis(), "signing request as "
            // + authHeader.getValue());
        }
    } catch (Exception e) {
        throw new HttpException("OAuth request interceptor failed", e);
    }
}
```

}
