### ISSUE TITLE
Change Image Cache Directory to Android/Data/{package}/*

### ISSUE THREAD

**Issue by abombss** [mttkay/droid-fu#20]
Per android v8 using a proper directory sdcard/Android/Data/{package}/\* will cause the data to be deleted on uninstall.

**Comment by mttkay** [comment]
interesting, is this behavior documented somewhere?

**Comment by abombss** [comment]
http://developer.android.com/guide/topics/data/data-storage.html#filesExternal

It currently only works for API 8+, but its good practice
