### ISSUE TITLE
Add .nomedia file to the image cache directory

### ISSUE THREAD

**Issue by abombss** [mttkay/droid-fu#21]
Per android doc, add a ".nomedia" file to the image cache directory to ensure its not caught by the media scanner and added to the gallery.

**Comment by mttkay** [comment]
great input here, thanks. again, this is new to me, do you have a link to where this is documented?

**Comment by abombss** [comment]
Same spot as the files and cache dir, its on the sidebar.
http://developer.android.com/guide/topics/data/data-storage.html#filesExternal

**Comment by mttkay** [comment]
thanks, appreciated. I always miss changes made to these documents as most of them have been there for quite a long time.
