### ISSUE TITLE
ImageCache.getBitmap throws OutOfMemoryError (bitmap size exceeds VM budget)

### ISSUE THREAD

**Issue by bumbobway** [mttkay/droid-fu#27]
Hello,
Thanks for making this awesome cache library. Everything in your library is working well, but I noticed that in my Android Market crash reports, there is a crash originating from droid-fu. (two reports in the last week).

I am using ImageLoader to fetch small 48x48 images, three at a time, approximately every thirty seconds. The image size is quite small (12kb each). 

Could the in-memory cache be filling up?

I am building with the Android 1.6 library. 

Here is the Stack trace
java.lang.OutOfMemoryError: bitmap size exceeds VM budget
at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:392)
at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:405)
at com.github.droidfu.cachefu.ImageCache.getBitmap(ImageCache.java:67)
at com.github.droidfu.imageloader.ImageLoader.start(ImageLoader.java:153)
at com.github.droidfu.imageloader.ImageLoader.start(ImageLoader.java:121)

**Comment by mttkay** [comment]
That's odd. We load much bigger images and only very rarely saw this happening on older devices. A 12KB image should certainly not cause an OOM, unless there is a larger memory leak elsewhere.

The cache is implemented using soft references, and it's at the GC's discretion when to clear them. That's of course unless there are still strong references to those images around. Could it be that in your app you keep references to the loaded and cached images around? That would prevent them from being garbage collected. This happens for instance if you leak the views they're drawn on, or the bitmaps/drawables themselves.

**Comment by bumbobway** [comment]
Thanks for the fast response. I double-checked based on your recommendation to see if I am leaking the views. 

This is how the code works: 
- Every time I need to load new images, I call LinearLayout.removeAllViews to make sure the ImageButton objects are GC'ed. 
- I fetch the image through the cache using ImageLoader.start(iconUrl, imageButton); [ImageButton is a standard Android ImageButton control, which derives from ImageView]
- I programmatically display the ImageButtons in a LinearLayout using addView.

**Comment by mttkay** [comment]
just curious, why are you completely removing and re-adding all views? that's not what you should usually do. If you merely want to refresh the image, then step 2 is all you need. Android will make sure the ImageView is redrawn whenever you call setImageDrawable or setImageBitmap.

**Comment by bumbobway** [comment]
Good point. The code was initially designed to show a variable number of images, between one and three. Adding and removing each time was simply easier at first. I need to make this more efficient.

I can however, just hide the ones I'm not using instead of add/removing them. I'll add that logic in, then I'll check MarketPlace over the next few weeks to see if that solves the problem for my users. If I see the problem return, I will get back to you.

Thanks for the tip!

**Comment by bumbobway** [comment]
Seems to be working fine by reusing the view. Closing issue.

**Comment by istashak** [comment]
I'm seeing the same issue while using the WebImageView, which uses ImageLoader.start(...).  Any thoughts on what I might be doing wrong?

Here's the exception stack:

E AndroidRuntime: java.lang.OutOfMemoryError: bitmap size exceeds VM budget
E AndroidRuntime: at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
E AndroidRuntime: at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:392)
E AndroidRuntime: at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:405)
E AndroidRuntime: at com.github.droidfu.cachefu.ImageCache.getBitmap(ImageCache.java:67)
E AndroidRuntime: at com.github.droidfu.imageloader.ImageLoader.setOrLoadImage(ImageLoader.java:185)
E AndroidRuntime: at com.github.droidfu.imageloader.ImageLoader.start(ImageLoader.java:178)
E AndroidRuntime: at com.github.droidfu.widgets.WebImageView.loadImage(WebImageView.java:161)

**Comment by mttkay** [comment]
well probably the images you're trying to load don't fit in your application's heap. How big on average are these images? I doubt it's a bug in ImageLoader/ImageCache, since we have been using that on plenty of devices for way over a year now without any problems.

double check your code whether you're not leaking references, too.
