### ISSUE TITLE
Missing method to forecefully purge disk cache

### ISSUE THREAD

**Issue by gradha** [mttkay/droid-fu#45]
It would be nice to have a public static method to clean the SD disk cache on request, rather than waiting for the automatic expiration to happen.

**Comment by mttkay** [comment]
AbstractCache implements clear():

```
public synchronized void clear() {
    cache.clear();

    if (isDiskCacheEnabled) {
        File[] cachedFiles = new File(diskCacheDirectory).listFiles();
        if (cachedFiles == null) {
            return;
        }
        for (File f : cachedFiles) {
            f.delete();
        }
    }

    Log.d(LOG_TAG, "Cache cleared");
}
```

is that what you're looking for?

**Comment by gradha** [comment]
Ok, so would it be enough to call HttpResponseCache.getResponseCache().clear() and ImageLoader.clearCache() to reach that method?

**Comment by mttkay** [comment]
What do you mean? It's a public method, you can call it from anywhere in your app. A method doesn't have to be static to be callable :-)

**Comment by gradha** [comment]
Thanks.
