### ISSUE TITLE
proguard

### ISSUE THREAD

**Issue by robbypond** [mttkay/droid-fu#53]
Having trouble getting this to work properly with proguard. Can some instructions be added to the wiki? Thanks!

**Comment by mttkay** [comment]
Try adding these rules and let me know if it helps:

```
-keep class com.google.common.base.Finalizable* {
  <fields>;
  <methods>;
}

-keep class com.google.common.base.internal.Finalizer {
  <fields>;
  <methods>;
}
```

**Comment by robbypond** [comment]
Thanks that seemed to do the trick.
