### ISSUE TITLE
Could the cache length of BetterHttp be made non-static?

### ISSUE THREAD

**Issue by rsaunders100** [mttkay/droid-fu#55]
Currently to configure the cache I use somthing like this:

```
 BetterHttp.enableResponseCache(context, 10, cacheLengthMins, 4, AbstractCache.DISK_CACHE_INTERNAL);
```

It would be nice to have multiple instances of the HTTP each with different cache lengths.

Perhaps you could have to option to overide the cache length on individual requests, e.g. 

```
BetterHttpRequest request = BetterHttp.get(_url, _useCache);
request.setCachelLength(cacheLengthMinsShort);   // Override the default cache length

BetterHttpRequest request2 = BetterHttp.get(_url2, _useCache);
request2.setCachelLength(cacheLengthMinsLong);   // Override the default cache length

BetterHttpRequest request3 = BetterHttp.get(_url3, _useCache); 
// Will have the default cache length set from enableResponseCache
```

Also would be nice if this could be done for connection time outs too (`BetterHttp.setSocketTimeout`)

Love the project by the way.
Cheers,
Rob.

**Comment by mttkay** [comment]
Hi, we're currently basically re-implementing Droid-Fu to make it more modular and make less use of statics. So yes, we have actually already fixed this. Since we made many changes to class names and package structure, we plan to re-launch it at some point (see https://github.com/kaeppler/ignition)

**Comment by rsaunders100** [comment]
Excellent, thanks for the response
