### ISSUE TITLE
Transparency lost for WebImageView

### ISSUE THREAD

**Issue by gatepoet** [mttkay/droid-fu#6]
When I use the WebImageView the image seems to loose transparency. It doesn't matter if I use my own xml layout or if I copy directly from your blog(part two).

One of the images I'm trying to display is:
http://nnug.no/images/scal/08_24.gif

This image gets a black background when using the WebImageView. When downloading the same image, adding it as a reference and display it using a regular ImageView the image displays correctly, with transparency.

Extracting the following code from the ImageLoader, using it directly in the ListAdapter also works:

ImageView image = (ImageView) row.findViewById(id);
URL url = new URL(imageUrl);
Bitmap bitmap = BitmapFactory.decodeStream(url.openStream());
image.setImageBitmap(bitmap);

**Comment by gatepoet** [comment]
I have tried around and I manage to reproduce the issue when I use the bitmap.compress() method.

It seems that the root of the issue is due to the CompressFormat statically being set to CompressFormat.JPEG.

My suggestion to solve this issue is to make the compression format configurable (the compression rate would also be nice). Maybe also PNG is a better first choice (if you don't have a special reason for choosion JPEG in the first place)

**Comment by mttkay** [comment]
Thanks for reporting -- yes, the decision to go for JPEG by default (I did that for space efficiency reasons, since the cache will grow big quickly with PNGs) has caused problems in other situations, too. I will look into this (I've been working on Droid-Fu again lately and will try to turn the project into a proper library project over the next 2-3 months)

**Comment by mttkay** [comment]
I've fixed this in a recent commit. You can now change the compress format using a setter AND I've set the default compress format to PNG (so I took the decision to prefer preservation of image quality over compress rate).

BTW, the compress ratio has always been configurable using a setter on the ImageCache.
